### ISSUE TITLE
Add GH credentials to the `Bumpver` GH Action

### ISSUE THREAD

**Issue by jonmatthis** [freemocap/skelly_viewer#17]
The `.github/workflows/bump_version_on_commit_to_main.yml` action fails because of missing credentials. 

e.g. this failed run - https://github.com/freemocap/skelly_viewer/actions/runs/10601758377/job/29382259688

I think there's a pretty easy way to add those creds using built in GH secrets (i.e. I don't think we need to make a whole new `secret` manually, like we do with the PYPI token in the `pypi` action) 

We might want to merge this `bumpver` action  with the `pypi` action when its working, or figure out how to compose them elegantly

**Comment by philipqueen** [comment]
I don't know if we need some further secret, but for now it was just failing because it needs a name and email set in git config. I made this change in #18

**Comment by roaldarbol** [comment]
Would it be possible to merge #18? It also seems to be the current cause for #19 failing the test (which is needed to move on with the conda packaging; same is true for the other skelly repos). :)

**Comment by philipqueen** [comment]
Fixed this! I also had to change the permissions settings in the action. It had read permissions, but changing the versions requires writing
